language: python
python: "3.7"

addons:
  apt:
    packages:
  sonarcloud:
    organization: "comran"
    token:
      secure: "Hr9D7hBY8W6Eu7ilpZItPpqiAHCr+xW7AjZlxWMjfUv2oNeYRlxqw/1yu8KwPVACXY8wcXWJU/ykJGGWNHi7uOm7hQQP3pBKdxgKO3eEPGulXFITL2kVXRJIGRAStxbsPbpg+S7dYu506hCe/lhnCZ+mDJ9XXQpPbR8XrLuwQlBeOwOzlc0otKpR1DKGoIEfStULl8zY7isJfF5BzjUkC5wXXZGoB46txDUg69x68p8Ov4AgG+B/8QQGt8F+EUAcbAJrETcqFuBbDvQ/aCMxlFUGchnZqQgG3I4wMKNAZusnPA6+7d8m+ndmxrQZL2qqWxOoWL/k8S59Li7TJ+60bCUK1aw9GDPpyNfyic9P0kitwlpwfJy5XLZSqgCctIVlvCw7cj1vdS0Ly0vlR9fE71+8gcpMSdxgBXJFal9VbFE3B2AKKFsULbGM2CLLVLf+LB646x9F3erbvOU0sTGsKIvEKqC9DlnqfAd/uWH+t/+8SqZnXa/bMXP4G6dGXiVpOf8ehqdvU09++DrdQD+NJ8Gyt1GCUM2vj6vhd9E1uuL9ZIAP7BAKVv2L8JMbrdgqkMwH44zFRGMTFhHzgKddLjj6tAirS8IJlg+gMSwyEJjKf1fYyjkjydgQfdkcnlDYTj0/FVndP3TNP9ePvNaeKnCTXGgbgso8iypk+fmUlb4="

install:
  - pip install numpy opencv-python  

script:
  - sonar-scanner -X
